name: My Practice Workflow

on: push 

jobs: 
    first_job:
      runs-on: ubuntu-latest
      steps:
       - name: Checkout Repo
         uses: actions/checkout@v4

       - name: List and Read Files
         run: |
            echo "Github in Action Job"
            ls -ltra
            cat README.md
       
       #- name: List files
        # run: ls
         
       #- name: Read file
        # run: cat README.md

